
development:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.config.settings.app_name %>_development
  pool: 5
  username: janaheimbring
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: travis_ci_test
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'janaheimbring' %>
  password: <%= ENV['TRAVIS'] ? '' : 'password' %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.config.settings.app_name %>_production
  pool: 5
  username: janaheimbring
  password: <%= ENV['DB_PASSWORD'] %>
